In [1]:
import numpy as np

In [2]:
import random

In [3]:
from q1_softmax import softmax
from q2_sigmoid import sigmoid, sigmoid_grad
from q2_gradcheck import gradcheck_naive

In [247]:
N = 20
dimensions = [10, 5, 10]
data = np.random.randn(N, dimensions[0])   # each row will be a datum
labels = np.zeros((N, dimensions[2]))
for i in xrange(N):
    labels[i, random.randint(0,dimensions[2]-1)] = 1

params = np.random.randn((dimensions[0] + 1) * dimensions[1] + (
    dimensions[1] + 1) * dimensions[2], )

In [248]:
ofs = 0
Dx, H, Dy = (dimensions[0], dimensions[1], dimensions[2])

W1 = np.reshape(params[ofs:ofs+ Dx * H], (Dx, H))
ofs += Dx * H
b1 = np.reshape(params[ofs:ofs + H], (1, H))
ofs += H
W2 = np.reshape(params[ofs:ofs + H * Dy], (H, Dy))
ofs += H * Dy
b2 = np.reshape(params[ofs:ofs + Dy], (1, Dy))

In [249]:
hidden = sigmoid(np.dot(data, W1) + b1) # N x H, 20x5
output = softmax(np.dot(hidden, W2) + b2)
cost = - np.sum(np.log(output) * labels)

ValueError: operands could not be broadcast together with shapes (20,10) (20,) 

In [60]:
dJ_dtheta = cost - labels
dtheta_dh = W2
dtheta_dW2 = hidden
dtheta_db2 = np.ones((1, Dy))
dh_dbeta = sigmoid_grad(np.dot(data, W1) + b1)
dbeta_dW1 = data
dbeta_db1 = np.ones((1, H))

In [62]:
dJ_dtheta.shape

(20, 10)

In [63]:
W2.shape

(5, 10)

In [68]:
dh_dbeta.shape

(20, 5)

In [69]:
dbeta_dW1.shape

(20, 10)

In [70]:
W1.shape

(10, 5)

In [72]:
hidden.shape

(20, 5)

In [76]:
(data.dot(W1) +  b1).shape

(20, 5)

In [97]:
labels.shape

(20, 10)

In [99]:
for row in data[:3]:
    print row

[ 0.28094469  0.05838513 -0.57292275 -0.58657765 -0.00440052 -0.34969839
 -0.03307242  0.16648636 -0.03766789 -0.97559039]
[ 0.19624867  0.7555675   1.56244809  0.36754698  0.73859973  0.27086583
  2.70356494  0.40993199  0.33580741 -1.26258536]
[ 0.00229612  0.43271026 -0.4898889   2.06249239 -0.66976959  0.87766948
  0.49844395 -0.6613306  -0.57693836 -0.23325953]


In [116]:
dJ_dtheta[1]

array([ 0.00931875,  0.22185168,  0.03122609,  0.09185805, -0.83969607,
        0.11780341,  0.01053529,  0.25390081,  0.03263838,  0.0705636 ])

In [118]:
W2.shape

(5, 10)

In [243]:
delta2 = W2.dot(dJ_dtheta[0])

In [244]:
delta2

array([ 1.28273983,  0.15972019,  0.7864384 ,  0.43341839, -0.9865888 ])

In [239]:
delta2[1]

array([ 0.15972019])

In [130]:
test = (np.reshape(W2.dot(dJ_dtheta[1]),(5,1))).dot(np.reshape(data[1], (1,10)))

In [131]:
test.shape

(5, 10)

In [227]:
hidden_grad = sigmoid_grad(np.dot(data, W1) + b1)

In [237]:
hidden_grad[1]

array([ -2.48056829e+01,  -5.14881068e-02,  -2.24986321e+00,
        -1.84750149e+01,  -5.65559084e+01])

In [230]:
delta1 = hidden_grad[1] * delta2

In [231]:
delta1

array([ -3.18192375e+01,  -8.22369022e-03,  -1.76937882e+00,
        -8.00741121e+00,   5.57974260e+01])

In [143]:
(np.reshape(data[1], (10,1)).dot(np.reshape(delta1, (1, 5)))).shape

(10, 5)

In [144]:
dJ_dtheta[1].shape

(10,)

In [148]:
hidden_grad[1].dot(np.reshape(dJ_dtheta[1], (1, 10)))

ValueError: shapes (5,) and (1,10) not aligned: 5 (dim 0) != 1 (dim 0)

In [220]:
dJ_dtheta.shape

(20, 10)

In [219]:
dJ_dtheta[0].shape

(10,)

In [150]:
delta1.shape

(5,)

In [151]:
params.shape

(115,)

In [153]:
cost.shape

(20, 10)

In [154]:
labels.shape

(20, 10)

In [218]:
cost * labels

array([[ 0.        ,  0.        ,  0.        ,  0.02429587,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.16030393,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.01136394,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.01238119,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.00909354,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.04836329,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.33228458,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        

In [173]:
results = (cost * labels).sum()

In [174]:
results

2.293909389823122

In [162]:
data.shape

(20, 10)

In [163]:
cache = np.zeros(data.shape)

In [164]:
cache[0][0] = 1.

In [242]:
data.shape[0]

20